# Generated by Django 5.0.2 on 2025-03-01 00:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moderator',
            name='forum_tag',
        ),
        migrations.AddField(
            model_name='forumreply',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='forumreply',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='disliked_replies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='forumreply',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_replies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='forumreply',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='forum.forumpost'),
        ),
    ]
