# Generated by Django 5.0.2 on 2025-03-01 01:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_remove_moderator_forum_tag_forumreply_pinned_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumreply',
            name='pinned',
        ),
        migrations.AlterField(
            model_name='forumreply',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='reply_dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='forumreply',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='reply_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='forumreply',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.forumpost'),
        ),
    ]
