# Generated by Django 5.0.2 on 2025-03-01 19:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_alter_forumpost_content_alter_forumpost_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='content',
            field=models.TextField(max_length=9999999, validators=[django.core.validators.MinLengthValidator(50)]),
        ),
    ]
